CREATE CONSTRAINT usuario_id IF NOT EXISTS FOR (n:Usuario) REQUIRE n.id_usuario IS UNIQUE;
CREATE CONSTRAINT cuenta_id IF NOT EXISTS FOR (n:Cuenta) REQUIRE n.id_cuenta IS UNIQUE;
CREATE CONSTRAINT transaccion_id IF NOT EXISTS FOR (n:Transaccion) REQUIRE n.id_transaccion IS UNIQUE;
CREATE CONSTRAINT dispositivo_id IF NOT EXISTS FOR (n:Dispositivo) REQUIRE n.id_dispositivo IS UNIQUE;
CREATE CONSTRAINT ubicacion_id IF NOT EXISTS FOR (n:Ubicacion) REQUIRE n.id_ubicacion IS UNIQUE;
CREATE INDEX usuario_nombre IF NOT EXISTS FOR (n:Usuario) ON (n.nombre);
CREATE INDEX cuenta_riesgo IF NOT EXISTS FOR (n:Cuenta) ON (n.nivel_riesgo);
CREATE INDEX transaccion_monto IF NOT EXISTS FOR (n:Transaccion) ON (n.monto);
CREATE INDEX transaccion_fecha IF NOT EXISTS FOR (n:Transaccion) ON (n.fecha);
CREATE INDEX dispositivo_confiable IF NOT EXISTS FOR (n:Dispositivo) ON (n.confiable);
